server:
  port: 7761

logging:
  level:
    root: DEBUG

spring:
  application:
    name: UserManagement
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


webprotege:
  rabbitmq:
    requestqueue: webprotege-user-management-queue
    responsequeue: webprotege-user-management-queue-response
    timeout: 60000
  keycloak:
    serverUrl: http://webprotege-local.edu/keycloak-admin
    realmName: webprotege
    clientId: user-management
    clientSecret: alcsial3ifVHn5wTlrIxXGOmKp743vd8
    username: admin
    password: password

