server:
  port: 7761

logging:
  level:
    root: DEBUG

spring:
  application:
    name: UserManagement
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


webprotege:
  rabbitmq:
    requestqueue: webprotege-user-management-queue
    responsequeue: webprotege-user-management-queue-response
    timeout: 60000
  keycloak:
    serverUrl: http://webprotege-local.edu/auth
    realmName: webprotege
    clientId: user-management
    clientSecret: 448ae58e-a9f0-4fab-92fe-650bfd5f9e57
    username: admin
    password: password

