server:
  port: 7761

logging.level.root: DEBUG

spring:
  application:
    name: UserManagement
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


webprotege:
  rabbitmq:
    requestqueue: webprotege-user-management-queue
    responsequeue: webprotege-user-management-queue-response
    timeout: 60000
  keycloak:
    serverUrl: http://webprotege-local.edu/auth
    realmName: webprotege
    clientId: user-management
    clientSecret: d4c1e0f1-599f-411c-bc1b-0fafb05424ac
    username: admin
    password: password

